### PR TITLE
Make `mentionRegex` stricter

### PR DESCRIPTION
**Pull request by HoodieRocks**
### Description

This pull request addresses an issue where the existing `mentionRegex` was being matched in unintended contexts, such as emails and URLs containing the "@" symbol. The proposed changes make the `mentionRegex` stricter to prevent false positives and improve the accuracy of mentions in the `remark-mentions` plugin.

### Changes Made

- Modified the `mentionRegex` to make it stricter and prevent unintended matches in emails and URLs containing "@" symbols.
- Added a new test case to validate the correctness of the updated `mentionRegex` implementation.

### Checklist

- [x] Updated `mentionRegex` to be stricter and more accurate.
- [x] Added a new test case to cover the changes.
- [x] Verified that all existing tests pass with the updated regex.
- [x] Ran the test suite locally to ensure compatibility.

This pull request aims to enhance the accuracy of the `remark-mentions` plugin and improve its behaviour when dealing with mentions in various contexts. Please review and provide feedback.

Thank you!

### CODE REVIEW

**Comment by FinnRG** [comment]
Thank you for your PR. Lookbehind assertions have only recently gained support in safari, so could you maybe replace `(?<!\S)` with just `\s` or would this introduce other edge cases?

**Comment by HoodieRocks** [comment]
`\s` can capture a leading space, which messes up parsing, resulting in something like:


```
source:   'This is @test'
expected: 'This is [**@test**](/test)\n'
actual:   'This is[** @test**](/test)\n'
```

Any mention that's at the beginning of a line won't be picked up, but that can be fixed with `($:^|\s)`. 

Do you have a suggestion for trimming the space?

**Comment by FinnRG** [comment]
@HoodieRocks Good point, what if we use `(?:^|\s)` and separate the leading white space in the replaceMention function like this (just a rough draft):

```js
  function replaceMention(value, username) {
    let whitespace = [];
    // Separate leading white space
    if (value.indexOf("@") > 0) {
      whitespace.push({
        type: "text",
        value: value.substring(0, value.indexOf("@")),
      });
    }

    return [
      ...whitespace,
      {
        type: "link",
        url: opts.usernameLink(username),
        children: [
          { type: "strong", children: [{ type: "text", value: value.trim() }] }, // Trim the username here
        ],
      },
    ];
  }
```

**Comment by HoodieRocks** [comment]
That code worked perfectly. The only difference I made was adding the type.

**Comment by FinnRG** [comment]
Thank you for your PR. I'll publish version 1.1 shortly.

**Pull request merged**
